-- 시드/핵심 엔티티 테이블을 Flyway로 확정 생성.
-- 기존에는 Hibernate ddl-auto=update에만 의존했으나, 서버 이전/부팅 실패 시
-- 테이블이 누락되어 DatabaseSeedInitializer가 크래시하는 문제를 방지한다.
-- 모두 IF NOT EXISTS 라 ddl-auto가 이미 만든 DB에서도 안전하게 통과한다.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    nickname VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    fcm_token VARCHAR(1000),
    oauth_provider VARCHAR(50),
    oauth_id VARCHAR(255),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    avatar_text VARCHAR(10) NOT NULL,
    weekly_learning_count INTEGER NOT NULL,
    quiz_accuracy_percent INTEGER NOT NULL,
    weak_topic VARCHAR(120) NOT NULL,
    CONSTRAINT uk_user_profiles_user_id UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS user_notification_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    before_30m BOOLEAN NOT NULL,
    important_event_briefing BOOLEAN NOT NULL,
    learning_reminder BOOLEAN NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_notification_settings_user_id UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS watch_asset_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_name VARCHAR(120) NOT NULL,
    default_change_percent DOUBLE PRECISION NOT NULL,
    display_order INTEGER NOT NULL,
    CONSTRAINT uk_watch_asset_catalog_asset_name UNIQUE (asset_name)
);

CREATE TABLE IF NOT EXISTS user_watch_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    asset_name VARCHAR(120) NOT NULL,
    change_percent DOUBLE PRECISION NOT NULL,
    signal_text VARCHAR(120) NOT NULL,
    display_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS policy_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    keyword VARCHAR(120) NOT NULL,
    impact_score DOUBLE PRECISION NOT NULL,
    analysis_summary VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
